version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    ports:
        - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./sqlinit/init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 2385
        MYSQL_DATABASE: lab6
